ingress:
  hosts:
    - host: home.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-secret
      hosts:
        - home.dev.demo.catena-x.net
service:
  environment: "DEV"
  